// generated by @ng-toolkit/universal
// const port = process.env.PORT || 4000;

// const server = require('./dist/server');

// server.app.listen(port, () => {
//     console.log(`Listening on: http://localhost:4000`);
// });
const port = process.env.PORT || 7100;

const server = require('./dist/server');

server.app.listen(port, () => {
    console.log(`Listening on: http://localhost:${port}`);
});